name: food_app
description: A new Flutter project.

publish_to: 'none'




version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

 
  cupertino_icons: ^1.0.2
  #DI
  get_it: ^7.2.0

  #STATE_MANAGEMENT
  stacked: ^3.2.1
  stacked_services: ^1.0.2
  stacked_generator: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:

  
  uses-material-design: true

  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

 